const llmService = require("./llmService");
const gitlabService = require("./gitlabService");
const confluenceService = require("./confluenceService");
const dbService = require("./dbService");
const logger = require("../utils/logger");

// Feature flag
const USE_LLM = process.env.USE_LLM === "true";

/**
 * Fallback (mock) flows when OpenAI is disabled
 */
function getMockFlows() {
  return [
    {
      name: "GitLab Webhook Receiver Flow",
      description: "Handles merge request webhook processing"
    }
  ];
}

/**
 * Fallback (mock) documentation when OpenAI is disabled
 */
function getMockDocumentation(flow, action) {
  return `
<h1>${flow.name}</h1>

<p><b>Action:</b> ${action.toUpperCase()}</p>

<h2>Overview</h2>
<p>
This documentation is auto-generated in fallback mode.
OpenAI integration is currently disabled.
</p>

<h2>Flow Description</h2>
<p>
${flow.description || "N/A"}
</p>

<h2>Notes</h2>
<ul>
  <li>Source: GitLab Merge Request</li>
  <li>Generated by ai-analyzer service</li>
</ul>
`;
}

exports.processMergeRequest = async (payload) => {
  logger.info(`🚀 Processing MR ${payload.mr_id}`);

  // 1️⃣ Fetch GitLab code context
  const codeContext = await gitlabService.expandContext(payload);

  // 2️⃣ Identify flows
  let flows;
  if (USE_LLM) {
    logger.info("🤖 Identifying flows via OpenAI");
    flows = await llmService.identifyFlows(codeContext);
  } else {
    logger.warn("⚠️ OpenAI disabled. Using mock flows.");
    flows = getMockFlows();
  }

  // 3️⃣ Process each flow
  for (const flow of flows) {
    logger.info(`➡️ Processing flow: ${flow.name}`);

    // DB lookup
    const existingPage = await dbService.findFlow(flow.name);

    const action = existingPage ? "update" : "create";

    // 4️⃣ Generate documentation
    let documentation;
    if (USE_LLM) {
      logger.info(`✍️ Generating ${action} documentation using OpenAI`);
      documentation = await llmService.generateDocumentation({
        flow,
        context: codeContext,
        action
      });
    } else {
      logger.warn("⚠️ OpenAI disabled. Using mock documentation.");
      documentation = getMockDocumentation(flow, action);
    }

    // 5️⃣ Write to Confluence
    if (existingPage) {
      logger.info(`📘 Updating existing Confluence page for ${flow.name}`);
      await confluenceService.updatePage(
        existingPage.pageId,
        flow.name,
        documentation,
        existingPage.version
      );
    } else {
      logger.info(`📄 Creating new Confluence page for ${flow.name}`);
      const pageId = await confluenceService.createPage(
        flow.name,
        documentation
      );
      await dbService.saveFlow(flow.name, pageId);
    }

    logger.info(`✅ Flow processed successfully: ${flow.name}`);
  }

  logger.info("🎉 Merge Request processing completed");
};
